let input = await Bun.file('input.txt').text()

// input = `.......S.......
// ...............
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............`

const splitters = input.split('\n').map(x => x.split('').map((x, i) => x == '^' || x == 'S' ? i : null).filter(x => x != null)).filter(x => x.length != 0)


let beams: number[] = splitters.shift()!
const total = splitters.length
let i = 0
for (const splitter of splitters) {
    i++
    const intersection = beams.filter(x => splitter.includes(x))
    const newBeams: number[] = []
    intersection.forEach(x => newBeams.push(x - 1, x + 1))
    beams = beams.filter(x => !intersection.includes(x))
    beams.push(...newBeams)
    console.log(i, total)
}

console.log(beams.length)