let input = await Bun.file('input.txt').text()

// input = `.......S.......
// ...............
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............`

const splitters = input.split('\n').map(x => x.split('').map((x, i) => x == '^' || x == 'S' ? i : null).filter(x => x != null)).filter(x => x.length != 0)

let sum = 0

let beams: Set<number> = new Set(splitters.shift()!)
for (const splitter of splitters) {
    const intersection = beams.intersection(new Set(splitter))
    sum += intersection.size
    intersection.forEach(x => (beams.delete(x), beams.add(x - 1), beams.add(x + 1)))
}

console.log(sum)